name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn --frozen-lockfile
      - run: yarn test
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Vercel
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Do something with a passing build
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: echo "success"
      - name: Do something with a failing build
        if: steps.wait-for-build.outputs.conclusion == 'failure'
        run: echo "fail"
