name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile
      - run: yarn test
  e2e-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e
    steps:
      - uses: actions/checkout@v2
      - run: yarn --frozen-lockfile
      - name: Wait for deployment
        id: wait-for-netflify
        uses: jakepartusch/wait-for-netlify-action@v1.2
        with:
          site_name: "proptypes"
      - run: yarn test
        env:
          ENVIRONMENT_URL: ${{ steps.wait-for-netflify.outputs.url }}
