name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn test
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Setup Playwright
        uses: microsoft/playwright-github-action@v1
      - run: yarn --frozen-lockfile
      - run: yarn start &
        working-directory: web
      - run: yarn test
        working-directory: e2e
      - name: Upload screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: e2e/screenshots/*.png
